import { webcrypto } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { loadTasks, saveTasks, saveVerifiedTasks, clearTasks } from "@/features/persistence/local-storage";
import { sha256 } from "@/features/evidence/lib/validation";
import { numericFixture } from "../fixtures/fictional-numeric";
import { appendNumericReviews } from "./history";
import { createNumericReview } from "./validation";
import { requestFromReview } from "./derive";
import { normalizeNumericTasks, verifyNumericTasks } from "./tasks";
import { verifiedNumericExport } from "./export";
const key = "evidenceloom.analysisTasks.v1";
beforeEach(() => { vi.stubGlobal("crypto", webcrypto); window.localStorage.clear(); });
describe("append-only retained numeric report authority", () => {
    it("rejects global version-ID owner/core rebinding without confusing identical run copies", async () => {
        const first = numericFixture(false), second = structuredClone(first);
        second.id = "other-task"; second.reportVersions[0].decision = "Buy";
        const normalized = normalizeNumericTasks([first, second]);
        expect(normalized.every((task) => task.reportVersions[0].numericValidation?.reason === "reference_mismatch")).toBe(true);
        await saveVerifiedTasks([first]); const before = window.localStorage.getItem(key);
        await expect(saveVerifiedTasks([first, second])).rejects.toThrow("reference_mismatch");
        expect(window.localStorage.getItem(key)).toBe(before);
        second.reportVersions[0].id = "distinct-version"; second.reportVersions[0].decision = "REVIEW";
        await saveVerifiedTasks([first, second]); expect(loadTasks().every((task) => !task.reportVersions[0].numericValidation)).toBe(true);
    });
    it("deep-copies the full snapshot/history through browser reload and permits exact idempotent append", async () => {
        const task = numericFixture(), version = task.reportVersions[0], original = structuredClone(task);
        const same = appendNumericReviews(task, version.id, version.numericReviews!);
        expect(same.reportVersions[0].numericReviews).toHaveLength(version.numericReviews!.length);
        await saveVerifiedTasks([same]);
        task.reportTextSnapshot!.report_sections.market_report = "CHANGED";
        const saved = (await verifyNumericTasks(loadTasks()))[0];
        expect(saved.reportVersions[0].numericReviews).toEqual(original.reportVersions[0].numericReviews);
        expect(saved.reportTextSnapshot).toEqual(original.reportTextSnapshot);
        expect(saved.evidenceBundle!.artifacts).toEqual(original.evidenceBundle!.artifacts);
        expect(saved.reportVersions[1].reportTextSnapshot).toBeUndefined();
        await expect(verifiedNumericExport(saved.id, saved.reportVersions[1])).resolves.toMatchObject({ numericReviews: [] });
    });
    it.each([false, true])("preserves actual localStorage authority when an invalid append is saved (verified=%s)", async (verified) => {
        const task = numericFixture();
        await saveVerifiedTasks([task]);
        const before = window.localStorage.getItem(key);
        const version = task.reportVersions[0], request = requestFromReview(version.numericReviews![1]);
        request.review_id = crypto.randomUUID();
        request.previous_review_sha256 = version.numericReviews!.at(-1)!.review_sha256;
        request.reviewed_at = "2026-01-09T13:00:00.000000Z";
        const forged = await createNumericReview(task.reportTextSnapshot!, task.evidenceBundle!, request);
        forged.result.status = "match";
        forged.result.reason = "value_match";
        const { review_sha256: _hash, ...body } = forged;
        void _hash;
        forged.review_sha256 = await sha256(body);
        version.numericReviews!.push(forged);
        if (verified)
            await expect(saveVerifiedTasks([task])).rejects.toThrow("reference_mismatch");
        else
            expect(() => saveTasks([task])).toThrow("reference_mismatch");
        expect(window.localStorage.getItem(key)).toBe(before);
    });
    it("rejects stale history, core rewrites, retained-version deletion and coherent snapshot replacement", async () => {
        const task = numericFixture();
        await saveVerifiedTasks([task]);
        const before = window.localStorage.getItem(key);
        const stale = structuredClone(task);
        stale.reportVersions[0].numericReviews!.pop();
        await expect(saveVerifiedTasks([stale])).rejects.toThrow("reference_mismatch");
        const core = structuredClone(task);
        core.reportVersions[0].decision = "Buy";
        expect(() => saveTasks([core])).toThrow("reference_mismatch");
        const removed = structuredClone(task);
        removed.reportVersions.shift();
        expect(() => saveTasks([removed])).toThrow("reference_mismatch");
        const changed = structuredClone(task), snapshot = changed.reportTextSnapshot!;
        snapshot.report_sections.market_report += " altered";
        const { snapshot_sha256: _hash, ...body } = snapshot;
        void _hash;
        snapshot.snapshot_sha256 = await sha256(body);
        changed.reportSections = structuredClone(snapshot.report_sections);
        changed.reportVersions[0].reportTextSnapshot = structuredClone(snapshot);
        changed.reportVersions[0].reportSections = structuredClone(snapshot.report_sections);
        changed.reportVersions[0].numericReviews = [];
        await expect(saveVerifiedTasks([changed])).rejects.toThrow("reference_mismatch");
        expect(window.localStorage.getItem(key)).toBe(before);
    });
    it("propagates same-run snapshot conflicts to every owner before clearing any attachment", async () => {
        const first = numericFixture(false), changed = structuredClone(first), follower = structuredClone(first);
        changed.reportTextSnapshot!.report_sections.market_report += " ";
        const { snapshot_sha256: _hash, ...body } = changed.reportTextSnapshot!;
        void _hash;
        changed.reportTextSnapshot!.snapshot_sha256 = await sha256(body);
        changed.reportSections = structuredClone(changed.reportTextSnapshot!.report_sections);
        follower.id = "follower";
        follower.reportVersions[0].id = "follower-version";
        const safe = normalizeNumericTasks([changed, follower]);
        expect(safe.every((task) => task.numericValidation?.reason === "reference_mismatch" && task.reportVersions[0].numericValidation?.reason === "reference_mismatch")).toBe(true);
        await saveVerifiedTasks([changed, follower]);
        const saved = loadTasks();
        await expect(verifiedNumericExport(follower.id, saved[1].reportVersions[0])).rejects.toThrow("reference_mismatch");
        expect(saved[1].evidenceBundle!.artifacts).toEqual(first.evidenceBundle!.artifacts);
    });
    it("permits identical snapshot copies and whole-task deletion/clear without orphan authority", async () => {
        const task = numericFixture(false), second = structuredClone(task);
        second.id = "second";
        second.reportVersions[0].id = "second-version";
        await saveVerifiedTasks([task, second]);
        expect(loadTasks().every((item) => !item.numericValidation)).toBe(true);
        await saveVerifiedTasks([second]);
        expect(loadTasks()).toHaveLength(1);
        clearTasks();
        expect(loadTasks()).toEqual([]);
    });
    it("keeps invalid new attachments explicit while leaving legacy exports available", async () => {
        const task = numericFixture();
        task.reportVersions[0].numericReviews!.at(-1)!.review_sha256 = "f".repeat(64);
        await saveVerifiedTasks([task]);
        const saved = loadTasks()[0];
        expect(saved.reportVersions[0].numericValidation?.reason).toBe("hash_mismatch");
        await expect(verifiedNumericExport(saved.id, saved.reportVersions[0])).rejects.toThrow("hash_mismatch");
        await expect(verifiedNumericExport(saved.id, saved.reportVersions[1])).resolves.toBeDefined();
    });
});
