export const comparisonLabels = {
  en: {
    title: "Compare saved report versions", baseline: "Baseline", target: "Target",
    description: "Compare original saved text from two versions of this task. Changes do not establish better research, factual accuracy, or expert approval. Comparison choices are independent of single-version review and export.",
    needsVersions: "Two saved report versions are needed for comparison.",
    duplicateIds: "Saved version IDs are duplicated. Comparison is unavailable because version ownership is ambiguous.",
    unavailableIds: "Some saved versions have unsupported or missing IDs and cannot be selected for comparison.",
    unavailableMetadata: "Some saved version metadata is unavailable. Original section text is shown independently; missing context is not reconstructed.",
    sameVersion: "Both sides select the same saved version.",
    navigation: "Report section comparison", changed: "Changed", same: "Same", unavailable: "Cannot compare",
    changeCount: (count: number, unavailable: number) => `${count} of 7 original sections changed.${unavailable ? ` ${unavailable} sections could not be compared.` : ""}`,
    sections: {
      market_report: "Market Analysis", sentiment_report: "Sentiment Analysis", news_report: "News Analysis",
      fundamentals_report: "Fundamentals Analysis", investment_plan: "Research Team Decision",
      trader_investment_plan: "Trading Team Plan", final_trade_decision: "Portfolio Decision",
    },
    states: { missing: "Section not recorded", null: "Recorded null", empty: "Recorded empty string", whitespace: "Whitespace-only string", text: "Original saved text", unsupported: "Unsupported saved section value · unavailable" },
    escaped: "Inspect whitespace and line endings", original: "Original saved text",
    characters: (count: number) => `${count} characters, including whitespace`,
    versionId: "Version ID", runId: "Run ID", instrument: "Instrument", analysisDate: "Analysis date",
    createdAt: "Saved at", rating: "Rating", legacy: "Legacy version", yes: "Yes", no: "No",
    unknown: "Not recorded · unknown", manifest: "Saved run manifest", provider: "Provider and models",
    attachmentTitle: "Saved attachment status", attachmentNotice: "Saved attachment presence and recorded errors are shown here. Use single-version review to inspect validation results.",
    attached: "Saved · not revalidated here", invalid: "Recorded validation error",
    attachments: { evidence: "Evidence", memory: "Memory", readiness: "Readiness", numeric: "Original text / Numeric Review", identity: "Request identity" },
  },
  zh: {
    title: "比较保存的报告版本", baseline: "基线版本", target: "目标版本",
    description: "比较同一任务两个版本保存的原始文本。内容变化不证明研究更好、事实准确或获得专家认可。比较选项独立于单版本审阅与导出。",
    needsVersions: "保存两个报告版本后即可比较。", sameVersion: "两侧选择了同一个保存版本。",
    duplicateIds: "保存的版本 ID 重复，无法明确版本归属，暂不能比较。",
    unavailableIds: "部分保存版本的 ID 缺失或不受支持，不能选入比较。",
    unavailableMetadata: "部分保存的版本元数据不可用。原始章节文本独立显示，不会补造缺失的上下文。",
    navigation: "报告章节比较", changed: "有变化", same: "相同", unavailable: "无法比较",
    changeCount: (count: number, unavailable: number) => `7 个原始章节中有 ${count} 个发生变化。${unavailable ? `${unavailable} 个章节无法比较。` : ""}`,
    sections: {
      market_report: "市场分析", sentiment_report: "情绪分析", news_report: "新闻分析",
      fundamentals_report: "基本面分析", investment_plan: "研究团队决策", trader_investment_plan: "交易团队计划", final_trade_decision: "组合决策",
    },
    states: { missing: "未记录此章节", null: "记录为 null", empty: "记录为空字符串", whitespace: "仅含空白的字符串", text: "保存的原始文本", unsupported: "保存的章节值不受支持 · 无法比较" },
    escaped: "检查空白与换行符", original: "保存的原始文本",
    characters: (count: number) => `${count} 个字符（包含空白）`,
    versionId: "版本 ID", runId: "运行 ID", instrument: "证券", analysisDate: "分析日期", createdAt: "保存时间",
    rating: "评级", legacy: "历史版本", yes: "是", no: "否", unknown: "未记录 · 未知", manifest: "保存的运行配置", provider: "服务商与模型",
    attachmentTitle: "保存的附件状态", attachmentNotice: "此处显示保存的附件和已有错误；请在单版本审阅中查看校验结果。",
    attached: "已保存 · 此处未重新校验", invalid: "已记录的校验错误",
    attachments: { evidence: "证据", memory: "记忆", readiness: "输入检查", numeric: "原文快照 / 数值审阅", identity: "请求身份" },
  },
} as const;
