import type { ReportVersion, SystemLanguage } from "@/lib/types";
import type { ReportDocument, ReportDocumentSection } from "../types";

const reportGroups = [
  {
    id: "analyst-reports",
    keys: ["market_report", "sentiment_report", "news_report", "fundamentals_report"],
  },
  { id: "research-debate", keys: ["investment_plan"] },
  { id: "trading-plan", keys: ["trader_investment_plan"] },
  { id: "risk-and-portfolio", keys: ["final_trade_decision"] },
] as const;

const labels = {
  zh: {
    title: "Evidence Loom 研究报告",
    disclaimer: "本报告由概率模型和第三方数据生成，仅供研究参考，不构成金融、投资、法律或交易建议。",
    fictional: "完全虚构的演示报告：不对应任何真实证券、公司、价格、新闻或数据来源。",
    groups: ["分析师报告", "多空研究讨论", "交易计划", "风险讨论与最终决策"],
    reports: ["市场分析", "情绪分析", "新闻分析", "基本面分析", "研究团队决策", "交易团队计划", "组合决策"],
    metadata: ["任务 ID", "报告版本", "版本 ID", "证券", "分析日期", "生成时间", "资产类型", "研究深度", "分析师", "输出语言", "决策", "应用版本", "模型 Provider", "Quick Think 模型", "Deep Think 模型", "行情数据源", "技术指标数据源", "基本面数据源", "新闻数据源", "研究辩论轮数", "风险辩论轮数", "基准证券"],
    legacy: "历史版本未记录",
    rounds: "轮",
  },
  en: {
    title: "Evidence Loom Research Report",
    disclaimer: "This report is generated by probabilistic models and third-party data for research only. It is not financial, investment, legal, or trading advice.",
    fictional: "Entirely fictional demo report: it does not represent any real security, company, price, news item, or data source.",
    groups: ["Analyst Reports", "Bull/Bear Research Debate", "Trading Plan", "Risk Debate & Portfolio Decision"],
    reports: ["Market Analysis", "Sentiment Analysis", "News Analysis", "Fundamentals Analysis", "Research Team Decision", "Trading Team Plan", "Portfolio Decision"],
    metadata: ["Task ID", "Report Version", "Version ID", "Instrument", "Analysis Date", "Generated At", "Asset Type", "Research Depth", "Analysts", "Output Language", "Decision", "App Version", "LLM Provider", "Quick Think Model", "Deep Think Model", "Market Data", "Technical Indicators", "Fundamentals Data", "News Data", "Research Debate Rounds", "Risk Debate Rounds", "Benchmark"],
    legacy: "Not recorded for this historical version",
    rounds: "rounds",
  },
} as const;

export function buildReportDocument(
  taskId: string,
  origin: "analysis" | "demo",
  version: ReportVersion,
  language: SystemLanguage,
): ReportDocument {
  const text = labels[language];
  const instrument = [version.task.ticker, version.task.instrumentName].filter(Boolean).join(" · ");
  const runValues = version.run
    ? [
      version.run.appVersion,
      version.run.llmProvider,
      version.run.quickThinkLlm,
      version.run.deepThinkLlm,
      version.run.coreStockApis,
      version.run.technicalIndicators,
      version.run.fundamentalData,
      version.run.newsData,
      String(version.run.maxDebateRounds),
      String(version.run.maxRiskRounds),
      version.run.benchmarkTicker || "—",
    ]
    : Array.from({ length: 11 }, () => text.legacy);

  const metadataValues = [
    taskId,
    `v${version.versionNumber}`,
    version.id,
    instrument,
    version.task.analysisDate,
    version.createdAt,
    version.task.assetType,
    `${version.task.researchDepth} ${text.rounds}`,
    version.task.analysts.join(", "),
    version.task.outputLanguage,
    version.decision || "—",
    ...runValues,
  ];

  return {
    title: `${text.title}: ${version.task.ticker}`,
    disclaimer: text.disclaimer,
    fictionalNotice: origin === "demo" ? text.fictional : "",
    metadata: text.metadata.map((label, index) => [label, metadataValues[index] ?? "—"]),
    sections: buildSections(version, language),
    language,
    version,
  };
}

function buildSections(version: ReportVersion, language: SystemLanguage): ReportDocumentSection[] {
  const text = labels[language];
  const reportLabels = new Map([
    ["market_report", text.reports[0]],
    ["sentiment_report", text.reports[1]],
    ["news_report", text.reports[2]],
    ["fundamentals_report", text.reports[3]],
    ["investment_plan", text.reports[4]],
    ["trader_investment_plan", text.reports[5]],
    ["final_trade_decision", text.reports[6]],
  ]);

  return reportGroups.flatMap((group, groupIndex) => {
    const content = group.keys.flatMap((key) => {
      const report = version.reportSections[key]?.trim();
      if (!report) return [];
      return [`### ${reportLabels.get(key) ?? key}\n\n${report}`];
    }).join("\n\n");
    if (!content) return [];
    return [{ id: group.id, title: text.groups[groupIndex], content }];
  });
}
